site_name: GedCom Parser

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings:
    watch:
    - parsers

nav:
- home.md
- Code Reference:
  - parsers:
    - gedcom file: reference/parsers/gedcom_file.md
    - entry: reference/parsers/entry.md
