site_name: GedCom Parser
#
#
#plugins:
#- search
#- gen-files:
#    scripts:
#    - docs/gen_ref_pages.py
#- mkdocstrings:
#    handlers:
#      python:
#        selection:
#          docstring_style: numpy
#    watch:
#    - gedcom_parser
#- literate-nav:
#    nav_file: SUMMARY.md
#
plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- section-index
- mkdocstrings:
    watch:
    - gedcom_parser
    handlers:
      handlers:
        python:
          selection:
            docstring_style: numpy
- literate-nav:
    nav_file: SUMMARY.md

nav:
- Code Reference: reference/
